config/routes.rb
require 'sidekiq/web'
RailsScrapper::Application.routes.draw do
  get "batch/index"
  get "batch/export"

  get "batch/show"

  get "home/index"
  get "/single" => "home#single_crawl"
  get "/multi" => "home#multi_crawl"
  post "/do_crawl" => "home#do_crawl"
  get "/settings" => "home#settings"
  post "/update" => "home#update_settings"
  post "/upload" => "home#import"
  root :to => "home#index"
  mount Sidekiq::Web,  at: '/sidekiq'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  attr_accessible :finish_time, :keywords, :neg_keywords, :started_time, :status, :min_keywords, :updated_at
  classy_enum_attr :status
  has_many :sites, :dependent => :destroy
  accepts_nested_attributes_for :sites, :reject_if => lambda { |a| a.nil? }, :allow_destroy => true


  def csv_header
    "URL, Active, Business".split(', ')
  end
  
  def total_time(id)
  	if !finish_time.nil?
  	  seconds = Batch.find(id).sites.order("updated_at").last.updated_at - started_time
  	else
  	  #seconds = (DateTime.now.to_datetime - started_time.to_datetime).to_i
  	  seconds = 0
  	end
  	'%d days, %d hours, %d minutes, %d seconds' %
    # the .reverse lets us put the larger units first for readability
    [24,60,60].reverse.inject([seconds]) {|result, unitsize|
      result[0,0] = result.shift.divmod(unitsize)
      result
    }
  end
end

app/models/crawler.rb
require 'rubygems'
require 'timeout'
require 'addressable/uri'
require 'mechanize'
require 'to_regexp'
class Crawler
  attr_reader :matched_keywords, :quantity_to_match
  def initialize(url,keywords,neg_keywords,quantity_to_match)
    @url = url
    @title = title
    @keywords = keywords
    @neg_keywords = neg_keywords
    @matched_keywords = Hash.new
    @quantity_to_match =  quantity_to_match
    @isBusiness = false
    @isActive
  end
    def domain_name?(url)
      #domain_regex = /^((http|https):\/\/)[a-z0-9]*(\.?[a-z0-9]+)\.[a-z]{2,5}(:[0-9]{1,5})?(\/.)?$/ix
      domain_regex = /^https?:\/\//
      if !domain_regex.match(url).nil?
        status = true
      else
        @url = 'http://'+url
        status = false
      end
      if !domain_regex.match(@url).nil?
        status = true
      else
        status = false
      end
      status
    end

  def crawl  #Method will accept URL and Keywords will check each link agaisnt the keyword to detect if business
    if domain_name?(@url)
      agent = Mechanize.new
      agent.max_history=1
      agent.read_timeout=4
      agent.open_timeout=4
      agent.log = Logger.new "mmech.log"
      agent.user_agent_alias = 'Mac Safari'
      page = nil
      begin
	timeout(100) do
          page = agent.get(@url)
	end
          page.content_type
        if /html/.match(page.content_type).nil?
          @isActive = false
          @title = page.content_type
          return
        end
      #rescue Mechanize::ResponseCodeError => exception
      rescue Timeout::Error 
        @isActive = false
        return
      rescue StandardError => e
        #if exception.response_code == '400' or exception.response_code == '500'
          puts e
          @isActive = false
          return
        #end
      end
      @isActive = true
      @title = page.title
       url_uri = Addressable::URI.parse(@url.to_s)
      page.links.each do |link| #For every link in the page
        begin
          link.uri.to_s
          link_uri = Addressable::URI.parse(link.uri.to_s)
        rescue StandardError
          #puts StandardError
          next
        end
        @keywords.each do |keyword| #For every keyword provided
          str = "/"+keyword.to_s+"/" #Turn keyword into regexp
          regexp = str.to_regexp
          begin
	    (regexp.match(link.uri.to_s).nil? and regexp.match(link.text).nil?)
          rescue StandardError
            next
          end
	  if link_uri.host.nil? or url_uri.host == link_uri.host
	  #if !(/^\//.match(link.uri.to_s).nil?) or link.uri.to_s[0..@url.to_s.length-1] == @url 
	    if regexp.match(link.uri.to_s).nil? and regexp.match(link.text).nil?
	    else
              @matched_keywords[keyword] = link #HASH of matched keywords
            end
	  else
	    next
          end
        end
      end
      @isBusiness = true if @matched_keywords.values.uniq.count >= @quantity_to_match
    else
      @isActive = false
    end
      @neg_keywords.each do |neg|
        str2 = "/"+neg.to_s+"/"
        regexp2 = str2.to_regexp
        begin
          regexp2.match(page.parser.xpath('/html/body')[0].content).nil?
        rescue StandardError
          next
        end         
	if regexp2.match(page.parser.xpath('/html/body')[0].content).nil?
	  next
	else
	  @isBusiness = false
        end 
      end
      agent.shutdown
      agent = nil
  end

  def isBusiness
    @isBusiness
  end

  def url
    @url
  end

  def keywords
    @keywords
  end

  def isActive
    @isActive
  end

  def matched_keywords
    @matched_keywords
  end
  def title
    @title
  end
  def neg_keywords
    @neg_keywords
  end
end

app/models/keywords.rb
class Keywords < RailsSettings::CachedSettings
end

app/models/matched_link.rb
class MatchedLink < ActiveRecord::Base
  belongs_to :site
  attr_accessible :keyword, :link_text, :link_url
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :batch
  has_many :matched_links
  attr_accessible :scapped, :title, :url, :valid, :updated_at
  accepts_nested_attributes_for :matched_links, :reject_if => lambda { |a| a.nil? }, :allow_destroy => true
  def is_valid?
    "x" if self.valid_site
  end
  def is_business?
  	"x" if self.business
  end
end

app/models/test.rb
require './crawler'
require "benchmark"
  

 
  keywords = ['agency','services','mail','intl', 'STANDINGS', 'Carrer', 'Carrers', 'Inicio', 'Images', 'honda', 'These']
  c = Crawler.new('http://www.billfryer.com', keywords, 1)
  time = Benchmark.measure do
  	  c.crawl

  end
  puts c.isBusiness
  puts c.matched_keywords
puts time

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/batch_controller.rb
require 'csv'
class BatchController < ApplicationController
  def index
  	@batches = Batch.all
  end

  def show
  end

  def export
    @batch = Batch.find(params[:id])
    filename = "Batch_#{Date.today.strftime('%d%b%y')}"
    csv_data = CSV.generate do |csv|
      csv << @batch.csv_header
      @batch.sites.each do |c|
        row = [c.url, c.is_valid?, c.is_business?]
        csv << row
      end
    end
    send_data csv_data,
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=#{filename}.csv"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'csv'
  def index
  end
  def settings
    @settings = Setting
  end
  def update_settings
    Setting.keywords = params[:keywords]
    Setting.min_keywords = params[:min_keywords].to_i
    Setting.neg_keywords = params[:neg_keywords]
    redirect_to :back
  end
  def single_crawl
    @settings = Setting
  end
  def multi_crawl
    @settings = Setting
  end
  def do_crawl
    @settings = Setting
  	@keywords =[]
  	@keywords = @settings.keywords.split(",")
        @neg_keywords = @settings.neg_keywords.split(",")
  	@crawler = Crawler.new(params[:url],@keywords,@neg_keywords,Setting.min_keywords)
  	logger.debug "Keywords: " + @keywords.to_s
  	@crawler.crawl
  	@a = @crawler.isBusiness
  	logger.debug "Called business"
  end
  def import
    @settings = Setting
    @keywords = @settings.keywords
    @neg_keywords = @settings.neg_keywords
    if request.post? && params[:inputfile].present?
      infile = params[:inputfile].read
      n, errors = 0, []
      batch = Batch.create(:status => :started, :keywords => @keywords, :neg_keywords => @neg_keywords, :started_time => DateTime.now, :min_keywords => Setting.min_keywords)
      if batch.save
        BatchWorker.perform_async(batch.id,infile)
        redirect_to batch_index_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batch_helper.rb
module BatchHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/batch/index.html.erb
<h1>Batches</h1>

<table class="table table-bordered table-condensed">
	<thead class="table-bw">
		<tr>
			<th>Batch ID</th>
			<th>Status</th>
			<th>Keywords</th>
			<th>Started Time</th>
			<th>Finish Time</th>
			<th>Total Time</th>
			<th>Total Sites Crawled</th>
		</tr>
	</thead>
	<% @batches.each do |batch| %>
	<tr>
		<td><%= link_to batch.id, batch_export_path(:id =>batch.id) %></td>
		<td><%= batch.status %></td>
		<td><%= batch.keywords %></td>
		<td><%= batch.started_time %></td>
		<td><%= batch.finish_time %></td>
		<td><%= batch.total_time(batch.id) unless batch.sites.last.nil? %></td>
		<td><%= batch.sites.where(:scapped => true).count %></td>
	</tr>
	<% end %>
</table>


<div class="modal" id="myModal" style="display:none;">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Modal header</h3>
  </div>
  <div class="modal-body">
    <p>Shit</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>
</div>

app/views/batch/show.html.erb
<h1>Batch#show</h1>
<p>Find me in app/views/batch/show.html.erb</p>

app/views/home/_form.html.erb
<%= form_tag("/do_crawl", :method =>:post, :class=>"form-horizontal", :onsubmit=>"return $(this).validate()") do %>
  <div class="single-site-form">
  	<fieldset>
    	<legend>Single site validator</legend>
	  	<div class="field control-group">
	  		<%= label_tag :url, "URL", :class=>"control-label" %>
	  		<div class="controls">
	  			<%= text_field_tag(:url,nil,:class=>"input-large", :id=>"single-validate") %>
	  		    <p class="help-block">Insert the site URL. Example: http://www.google.com</p>
	  		</div>
	  	</div>
	  	<div class="field control-group">
	  		<%= label_tag :min_keywords, "Min. # Keywords", :class=>"control-label" %>
	  		<div class="controls">
	  			<%= text_field_tag(:min_keywords,@settings.min_keywords, :class =>"input-mini", :disabled=>true) %>
	  			<p class="help-block">Numbers of keywords to be matched in order for site be a Business</p>
	  		</div>
		</div>
	  	<div class="field control-group">
	  		<%= label_tag :keywords, "Keywords", :class=>"control-label" %>
	  		<div class="controls">
		 		<%= text_area_tag(:keywords,@settings.keywords,:class=>"input-large", :id =>"keywords-select", :style=>"width: 290px;", :disabled => true) %>
		 		<p class="help-block">Add keywords using , or tabs after each word</p>

	  		</div>
	  	</div>
	  	<div class="field control-group">
	  		<%= label_tag :neg_keywords, "Negative Keywords", :class=>"control-label" %>
	  		<div class="controls">
		 		<%= text_area_tag(:keywords,@settings.neg_keywords,:class=>"input-large", :id =>"neg-keywords-select", :style=>"width: 290px;", :disabled => true) %>
		 		<p class="help-block">Add negative keywords using , or tabs after each word</p>

	  		</div>
	  	</div>
	  	<div class="actions form-actions">
	  		<%= submit_tag("Crawl",:class=>"btn btn-primary") %>
  		</div>
	    <p class="help-block">Insert the site URL.</p>
	</fieldset>
  </div>
<% end %>

app/views/home/_table.html.erb
<table class="table table-bordered table-condensed">
	<thead class="table-bw">
		<tr>
			<th>URL</th>
			<th>Valid site?</th>
			<th>Business site?</th>
			<th>Keywords</th>
			<th>Min # of Keywords</th>
		</tr>
	</thead>
	<tr>
		<% unless @crawler.nil? %>
		<td><%= @crawler.url %></td>
		<td><%= @crawler.isActive %></td>
		<td><%= @crawler.isBusiness %></td>
		<td><%= @crawler.keywords %></td>
		<td><%= @crawler.quantity_to_match %></td>
	</tr>
</table>
<div class="span8">
	<h4>Keywords matched with internal links on <%= @crawler.url %></h4>
	<table class="table table-bordered table-condensed span6">
		<thead class="table-bw">
			<tr>
				<th>Keyword</th>
				<th>Internal link text</th>
				<th>Internal link url</th>
			</tr>
		</thead>
		<% @crawler.matched_keywords.each do |key,value| %>
		<tr>
			<td><%= key %></td>
			<td><%= value %></td>
			<td><%= value.uri %></td>
		</tr>
		<% end %>
	</table>
	<% end %>
</div>

app/views/home/do_crawl.html.erb
<%= render 'form' %>

<%= render :partial => 'home/table', :locals => { :parent => @crawler } %>

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Andre Web Crawling with Keywords</h1>
  <p>Crawling the web for business websites.</p>
  <h2>System Info: </h2>
  <ul>
  	<li>Ruby Version: <%= RUBY_VERSION %></li>
  	<li>Ruby on Rails Version: <%= Rails::VERSION::STRING %></li>
  	<li>Enviroment: <%= Rails.env %></li>
  </ul>
</div>

app/views/home/multi_crawl.html.erb
<%= form_tag("/upload", :class=>"form-horizontal", :onsubmit=>"return $(this).validate()", :multipart => true) do %>
  <div class="single-site-form">
  	<fieldset>
    	<legend>Multisite Validator</legend>
	  	<div class="field control-group">
	  		<%= label_tag :inputfile, "Input File", :class=>"control-label" %>
	  		<div class="controls">
	  			<%= file_field_tag :inputfile %>
	  		    <p class="help-block">Upload the file with the URL to be crawled.</p>
	  		</div>
	  	</div>
	  	<div class="field control-group">
	  		<%= label_tag :min_keywords, "Min. # Keywords", :class=>"control-label" %>
	  		<div class="controls">
	  			<%= text_field_tag(:min_keywords,@settings.min_keywords, :class =>"input-mini", :disabled=>true) %>
	  			<p class="help-block">Numbers of keywords to be matched in order for site be a Business</p>
	  		</div>
		</div>
	  	<div class="field control-group">
	  		<%= label_tag :keywords, "Keywords", :class=>"control-label" %>
	  		<div class="controls">
		 		<%= text_area_tag(:keywords,@settings.keywords,:class=>"input-large", :id =>"keywords-select", :style=>"width: 290px;", :disabled => true) %>
		 		<p class="help-block">Add keywords using , or tabs after each word</p>

	  		</div>
	  	</div>
	  	<div class="actions form-actions">
	  		<%= submit_tag("Process Data",:class=>"btn btn-primary") %>
  		</div>
	</fieldset>
  </div>
<% end %>

app/views/home/settings.html.erb
<div class="container">
  <div class="page-header">
    <h3>
      Application Settings
    </h3>
  </div>
  <h3>
    Keywords
  </h3>
  <%= form_tag("/update", :method =>:post, :class=>"form-horizontal") do %>
   <div class="field control-group">
        <%= label_tag :min_keywords, "Min. # Keywords", :class=>"control-label" %>
        <div class="controls">
          <%= text_field_tag(:min_keywords,@settings.min_keywords, :class =>"input-mini") %>
          <p class="help-block">Numbers of keywords to be matched in order for site be a Business</p>
        </div>
    </div>
      <div class="field control-group">
        <%= label_tag :keywords, "Keywords", :class=>"control-label" %>
        <div class="controls">
        <%= text_area_tag(:keywords,@settings.keywords,:class=>"input-large", :id =>"keywords-select", :style=>"width: 290px;") %>
        <a id="cl-btn" class="btn">Clear</a>
        <p class="help-block">Add keywords using , or tabs after each word</p>
        </div>
      </div>
      <div class="field control-group">
        <%= label_tag :neg_keywords, "Negative Keywords", :class=>"control-label" %>
        <div class="controls">
        <%= text_area_tag(:neg_keywords,@settings.neg_keywords,:class=>"input-large", :id =>"neg-keywords-select", :style=>"width: 290px;") %>
        <a id="cl-btn-n" class="btn">Clear</a>
        <p class="help-block">Add keywords using , or tabs after each word</p>
        </div>
      </div>
      <div class="actions form-actions">
        <%= submit_tag("Update Setting",:class=>"btn btn-primary") %>
        <button class="btn" onClick="this.form.reset()" type="button">Reset fields</button>
      </div>
  <% end %>
</div>

app/views/home/single_crawl.html.erb
<%= render 'form' %>

<%= render :partial => 'home/table', :locals => { :parent => @crawler } %>

app/views/layouts/_navigation.html.erb
<%= link_to "Andre Web Crawler", root_path, :class => 'brand' %>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="span2">
   <ul class="nav nav-list">
     <li><%= link_to "Home", root_path %></li>
     <li><%= link_to "Single Web Crawl", single_path %></li>
     <li><%= link_to "File upload Web Crawl", multi_path %></li>
     <li><%= link_to "Settings", settings_path %></li>
     <li><%= link_to "Batches", batch_index_path %></li>
   </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Business Validator - Web Crawler" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
           	<%= render :partial => 'layouts/sidebar' %>
            <div class="span10">
                <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>